version: "3.6"
services:
  hasura:
    image: hasura/graphql-engine:v2.1.0
    ports:
      - "8080:8080"
    restart: always
    environment:
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      ACTION_BASE_URL: ${ACTION_BASE_URL}

      #callisto:
      #  build:
      #    context: .
      #    dockerfile: Dockerfile
      #  restart: always
      #  command: callisto parse --home /callisto/.callisto
      #  volumes:
      #    ## Modify first path to match configuration file.
      #    - /callisto/.callisto:/callisto/.callisto
  postgres:
    image: postgres:13
    container_name: bdjuno-postgres
    environment:
      POSTGRES_DB: bdjuno
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./database/schema:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
